<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhAliadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhAliadosRepository extends \Doctrine\ORM\EntityRepository
{
}
