<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
