<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhCongresovshotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhCongresovshotelRepository extends \Doctrine\ORM\EntityRepository
{
}
