<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhCorreoContactoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhCorreoContactoRepository extends \Doctrine\ORM\EntityRepository
{
}
