<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhCongresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhCongresoRepository extends \Doctrine\ORM\EntityRepository
{
}
