<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhFooterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhFooterRepository extends \Doctrine\ORM\EntityRepository
{
}
