<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhHomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhHomeRepository extends \Doctrine\ORM\EntityRepository
{
    
}
