<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhIdiomasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhIdiomasRepository extends \Doctrine\ORM\EntityRepository
{
}
