<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhMenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhMenuRepository extends \Doctrine\ORM\EntityRepository
{
}
