<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhNosotrosRotadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhNosotrosRotadorRepository extends \Doctrine\ORM\EntityRepository
{
}
