<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhPaisCongresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhPaisCongresoRepository extends \Doctrine\ORM\EntityRepository
{
}
