<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhRedesSocialesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhRedesSocialesRepository extends \Doctrine\ORM\EntityRepository
{
}
