<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhReservaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhReservaRepository extends \Doctrine\ORM\EntityRepository
{
}
