<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhServiciosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhSeoEspecificoRepository extends \Doctrine\ORM\EntityRepository
{
}
