<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhTipoCongresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhTipoCongresoRepository extends \Doctrine\ORM\EntityRepository
{
}
