<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * ChhTestimonioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChhTestimonioRepository extends \Doctrine\ORM\EntityRepository
{
}
