<?php

namespace Hotel\ProjectBundle\Repository;

/**
 * PruebaIridianBDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PruebaIridianBDRepository extends \Doctrine\ORM\EntityRepository
{
}
